weather:
  api:
    url: https://api.openweathermap.org/data/2.5
    key: ${OPEN_WEATHER_API_KEY}

spring:
  main:
    allow-bean-definition-overriding: true

spring.autoconfigure:
  exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    -
spring.profiles:
    active: dev #prod